import React, {useState} from 'react';
import {Box, Button, Stack, Typography} from "@mui/material";
import AddBoxIcon from '@mui/icons-material/AddBox';

import CustomTypography from "../components/CustomTypography";
import ObjectType from "../components/objectTypes/ObjectType";
import PageLayout from "../layouts/PageLayout";
import ActivityEventType from "../components/eventTypes/ActivityEventType";
import useDataContext from "../dataContext/useDataContext";

function OcelMapping() {

    const [objectsTypesItem, setObjectsTypesItem] = useState([])

    // TODO: the following state should be the array with the object types to send via API for the backend
    const [objectTypesToMap, setObjectTypesToMap] = useState([])

    // TODO: the OCEL generated by the backend should be set here to display it in the frontend
    const {setOcel} = useDataContext()

    const handleAddObjectType = () => {
        setObjectsTypesItem([...objectsTypesItem, {name: "", names: []}])
    }

    // TODO: add a button to send the API request to the backend with the object types (objectTypesToMap) to map

    return (
        <PageLayout>
            <Box display="flex" justifyContent="center">
                <Box position="relative" height="100%" width={520} paddingBottom={2}>
                    <Typography variant="h3">
                        Data Mapping
                    </Typography>
                    <Stack marginY={3} height="calc(100vh - 300px)" overflow="auto">
                        <CustomTypography>
                            {"{"}
                        </CustomTypography>
                        <CustomTypography>
                            &nbsp;&nbsp;&nbsp;"eventTypes": [
                        </CustomTypography>
                        <ActivityEventType/>
                        <CustomTypography>
                            &nbsp;&nbsp;&nbsp;],
                        </CustomTypography>
                        <CustomTypography>
                            &nbsp;&nbsp;&nbsp;"objectTypes": [
                            {
                                <Button onClick={handleAddObjectType}>
                                    <AddBoxIcon sx={{fontSize: 30}}/>
                                </Button>
                            }
                            {objectsTypesItem.length === 0 && "],"}
                        </CustomTypography>
                        {objectsTypesItem.length > 0 &&
                            (
                                <>
                                    {objectsTypesItem.map((objectType, index) => (
                                        <ObjectType key={`${index}_object`}
                                                    setObjectsTypesItem={setObjectsTypesItem}
                                                    objectsTypesItem={objectsTypesItem} objectType={objectType}
                                                    index={index}/>
                                    ))}
                                    <CustomTypography>
                                        &nbsp;&nbsp;&nbsp;],
                                    </CustomTypography>
                                </>
                            )
                        }
                        <CustomTypography>
                            &nbsp;&nbsp;&nbsp;"events": []
                        </CustomTypography>
                        <CustomTypography>
                            &nbsp;&nbsp;&nbsp;"objects": []
                        </CustomTypography>
                        <CustomTypography>
                            {"}"}
                        </CustomTypography>
                    </Stack>
                </Box>
            </Box>
        </PageLayout>
    )
}

export default OcelMapping;